In [147]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model


In [148]:
df=pd.read_csv("homeprices.csv")

In [149]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
# nan  values is there 
#clean the data
#data preprocessing 

In [150]:
#calculating median will be good to assumption

#or we can take upper value or lower value

import math
median_bedrooms=df.bedrooms.median()
median_bedrooms

#here 4.0 came but this is infinity


4.0

In [52]:
#we can use this also

# median_bedrooms=math.floor(median_bedrooms)
# median_bedrooms


In [151]:
df.bedrooms.fillna(4)

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [152]:
#update main data frame
df.bedrooms=df.bedrooms.fillna(4.0)

In [153]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [154]:
#creation of model

reg=linear_model.LinearRegression()

In [155]:
#train the model
#df[[]]--independent variables
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [156]:
#finding coefficients

reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [157]:
#finding intercept
reg.intercept_

221323.00186540408

In [158]:
reg.predict([[4000,5.0,8]])

#pass 3 parameters area,bedrooms,years of age

array([760663.42675457])

In [67]:
?????????????? need to know about ploting with three variables

Object `???????????? need to know about ploting with three variables` not found.


In [159]:
#predict salary 
#2 year exp,9 test score,6 interview score


In [216]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [217]:
df=pd.read_csv("hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [218]:
#clean the data
df.rename(columns={'test_score(out of 10)':'test_score','interview_score(out of 10)':'interview_score','salary($)':'salary'},inplace=True)

In [163]:
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [219]:
# remove nan values 
df.test_score.median()

8.0

In [220]:
df.test_score.fillna(8)

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     8.0
7     7.0
Name: test_score, dtype: float64

In [221]:
#change in data frame

df.test_score=df.test_score.fillna(8)



In [222]:
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [223]:
#in experience  nan keep as zero years experience

df.experience=df.experience.fillna('zero')

In [178]:
df

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [224]:
#here strings is there 
#we cant predict strings change to numbers
# from word2number import w2n
#this will change word to number


In [226]:
# df.experience = df.experience.apply(w2n.word_to_num)
# df

#this proces is not working

In [227]:
df.experience[df.experience=='zero']=0
df.experience[df.experience=='five']=5

df.experience[df.experience=='two']=2

df.experience[df.experience=='seven']=7

df.experience[df.experience=='three']=3
df.experience[df.experience=='ten']=10

df.experience[df.experience=='eleven']=11



#here i m changing one by one by it changed for all by numbers ....why??????

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher

In [242]:
reg=linear_model.LinearRegression()

In [243]:
reg.fit(df[['experience','test_score','interview_score']],df.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [244]:
reg.predict([[0,8,9]])

#giving wrong answer

array([52350.0727802])

In [245]:
#using pickle to save the  train data becz we dont write all the time same code 
#we can give file to friends also they can easily pridict the data


import pickle
#wb is write -w  ,binary-b,....write in binary text

with open('reg_pickle','wb') as f:
    pickle.dump(reg,f)
    
#dump -append the data in file

#reg_pickle is non readable 

In [246]:
#now we have file  we can use that file and predict the data
#we r loading the data
#rb - read binary

with open('reg_pickle','rb') as f:
    newreg=pickle.load(f)
    
#load the data



In [247]:
newreg.predict([[12,6,23]])

#we can share the file to anyone we can use this file to predict thye data easily

array([113287.48180495])

In [248]:
#joblib same is as pickle but while large data set all will use jolib 
#joblib using bcz of using large numpy arrays

from sklearn.externals import joblib
joblib.dump('reg','reg_joblib')

#object file is created 

['reg_joblib']

In [249]:
#using file 
reg=joblib.load('reg_joblib')
reg.predict([[10,8,6]])

# reg.predict([[12,6,23]])


#showing error but process is same

AttributeError: 'str' object has no attribute 'predict'